### ISSUE TITLE
Upload Imagenet text files (provide links to get the text files)

### ISSUE THREAD

**Issue by rakashi** [dontfollowmeimcrazy/imagenet#1]
Hi
While I am training Imagenet data I didn't found the below two files 
meta.mat
ILSVRC2012_validation_ground_truth.txt
Can any one provide the above files

**Comment by dontfollowmeimcrazy** [comment]
Hello @rakashi 
you can find those files in the "Development kit (Task 1 & 2)" archive (inside the 'data' folder) in the ImageNet LSVRC 2012 download page.
