### ISSUE TITLE
ckpt-alexnet not found

### ISSUE THREAD

**Issue by sparsh2706** [dontfollowmeimcrazy/imagenet#12]
When i was running python classify.py ./lussaris.jpg,
It gave ckpt-alexnet not Found Error.
How can I resolve this?

**Comment by pengfeidip** [comment]
I have the same problem. There is no ckpt file

**Comment by matteo-dunnhofer** [comment]
Hi @sparsh2706 abd @pengfeidip!

Pre-trained checkpoint files are not provided in this repo. You have to train the model and save the weights yourself. After that classify.py will work.

**Comment by pengfeidip** [comment]
@dontfollowmeimcrazy  thank you!
