### ISSUE TITLE
IOError: cannot identify image file u'/home/ImageNet/ILSVRC2012/train/n01688243/n01688243_9115.JPEG'

### ISSUE THREAD

**Issue by sakshi404** [dontfollowmeimcrazy/imagenet#14]
I am getting following error while running your code: IOError: cannot identify image file u'/home/ImageNet/ILSVRC2012/train/n01688243/n01688243_9115.JPEG'
I got to know that some files are already corrupt in imageNet dataset. Could you please tell me how to resolve this issue.
Thanks

**Comment by matteo-dunnhofer** [comment]
Hi @sakshi404 

did you try to remove that file from the dataset? As you told, I think it is a corruption issue.
