### ISSUE TITLE
Please Upload ILSVRC2012 meta.mat,ILSVRC2012_validation_ground_truth.txt

### ISSUE THREAD

**Issue by rakashi** [dontfollowmeimcrazy/imagenet#7]
Hi
I am training ILSVRC2012 data using Alexnet Architecture, Here I am having train and validation data but I am not having the ILSVRC2012 meta.mat, ILSVRC2012_validation_ground_truth.txt. So I am using at meta.mat place I kept ILSVRC2014 meta.mat file and also I kept meta.mat ILSVRC2014_validation_ground_truth.txt

So here I am using 2012 dataset with 2014 meta.mat,ILSVRC2014_validation_ground_truth.txt.  I am thinking due to this files I am not getting image tags accurately ?

Please can any one upload ILSVRC2012 meta.mat and ILSVRC2012_validation_ground_truth.txt files, I have tried but I didn't get

**Comment by dontfollowmeimcrazy** [comment]
Hey @rakashi 

I explained how to download those files in #1 . From where did you download the ILSVRC2012 training images? From ImageNet's original website?

**Comment by rakashi** [comment]
thanks alot 
I have downloaded from Imagenet website Development kit (Task 1 & 2). In this folder contains meta.mat and ILSVRC2012_validation_ground_truth.txt
