### ISSUE TITLE
Can PIL be replaced with 'pillow' ?

### ISSUE THREAD

**Issue by jefflomax** [dontfollowmeimcrazy/imagenet#9]
There is no PIL import for Python 3.6.3, according to this post, PIL is abandoned and shouldn't be used.

https://www.reddit.com/r/Python/comments/5mph2q/how_do_you_install_pil_to_python_360/

**Comment by jefflomax** [comment]
For other Python newbies, pip install pillow to get around the missing import (compatible with Python 3.6.3)
from PIL import Image

And do not rename the import from PIL to pillow.  
(There goes the principal of least astonishment)

**Comment by dontfollowmeimcrazy** [comment]
Thank you @jefflomax !
